@ stdcall InitGetDevInfoWithCallbacks(str ptr ptr)
@ stdcall InitEtsEx(str str str str)
@ stdcall ReinitEtsEx(str)
@ stdcall RegisterProfileWithCallbacks(str ptr ptr ptr ptr ptr)
@ stdcall InitStackEx(str)
@ stdcall VerifyDongleEx()
@ stdcall GetDongleBDAddress()
@ stdcall StartDeviceSearchEx(str str str)
@ stdcall StopDeviceSearchEx(str)
@ stdcall GetDongleDeviceInformation()
@ stdcall GetDeviceList()
@ stdcall SetPTSDevice(str)
@ stdcall SetParameterEx(str str str str)
@ stdcall SetPostLoggingEx(long str)
@ stdcall StartTestCaseEx(str str long)
@ stdcall StopTestCaseEx(str str)
@ stdcall TestCaseFinishedEx(str str)
@ stdcall ExitStackEx(str)
@ stdcall UnregisterProfileEx(str)
@ stdcall UnRegisterGetDevInfoEx()
