name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Linux Dependencies
        run: sudo apt install -y bazel wine wine32-tools cabextract xvfb
      - name: Build
        run: cargo build --verbose
